// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import app "github.com/grupawp/tensorflow-deploy/app"
import context "context"
import mock "github.com/stretchr/testify/mock"

// ModelsReload is an autogenerated mock type for the ModelsReload type
type ModelsReload struct {
	mock.Mock
}

// ReloadConfig provides a mock function with given fields: ctx, team, project, skipConfigWithoutLabels
func (_m *ModelsReload) ReloadConfig(ctx context.Context, team string, project string, skipConfigWithoutLabels bool) ([]app.ReloadResponse, error) {
	ret := _m.Called(ctx, team, project, skipConfigWithoutLabels)

	var r0 []app.ReloadResponse
	if rf, ok := ret.Get(0).(func(context.Context, string, string, bool) []app.ReloadResponse); ok {
		r0 = rf(ctx, team, project, skipConfigWithoutLabels)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]app.ReloadResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string, string, bool) error); ok {
		r1 = rf(ctx, team, project, skipConfigWithoutLabels)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
